# Grant access to everything in the tilt-integration namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tilt-integration-user-full-access
  namespace: tilt-integration
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tilt-integration-user-view
  namespace: tilt-integration
subjects:
- kind: ServiceAccount
  name: tilt-integration-user
  namespace: tilt-integration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tilt-integration-user-full-access
---

# Grant access to nodes accross all namespaces
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tilt-integration-user-node-readonly-access
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tilt-integration-user-node-view
subjects:
- kind: ServiceAccount
  name: tilt-integration-user
  namespace: tilt-integration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tilt-integration-user-node-readonly-access
